Dz11
Otricali/homework_tms pull request #7
Opened 2023-03-30 14:05 UTC by Otricali

2023-03-31 13:58 UTC, vimoro requested changes

2023-03-31 13:58 UTC, vimoro commented on homework11.py
а почему ты закрыл прошлый PR и открыл новый? можно же было в прошлую ветку коммитить изменения, даже несмотря на то, что ты все переделал
следующий раз так не делай

2023-03-31 13:58 UTC, vimoro commented on homework11.py
> +    balance = 0
это должны быть не атрибуты класса, а атрибуты объектов класса, перенеси их в `__init__`

2023-03-31 13:58 UTC, vimoro commented on homework11.py
> +    def replenish(cls, amount):
то же самое и с методами, почему ты решил их делать методами класса, а не объекта?

2023-03-31 13:58 UTC, vimoro commented on homework11.py
> +print(account_transactions_1.get_balance())
вот если ты сейчас внимательно посмотришь на то, как работает твой код, то увидишь, что у первого аккаунта и у второго один баланс, а должны быть разные

2023-04-01 12:40 UTC, Otricali commented on homework11.py
> +print(account_transactions_1.get_balance())
так в этом и была суть, на одном аккаунте несколько транзакций, чтоб баланс запоминался я делал это через классовый метод

2023-04-01 12:47 UTC, Otricali commented on homework11.py
я не знал про это

2023-05-23 18:09 UTC, merged